# Generated by Django 4.2.1 on 2023-05-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_rename_pregunta_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElegirRespuesta',
            new_name='ChooseAnswer',
        ),
    ]
