# Generated by Django 4.2.1 on 2023-05-29 16:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz', '0007_rename_quizusuario_quizuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Pregunta',
        ),
        migrations.RenameModel(
            old_name='QuizUser',
            new_name='QuizUsuario',
        ),
    ]
