# Generated by Django 4.2.1 on 2023-05-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_rename_question_pregunta_rename_quizuser_quizusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='respuesa',
            new_name='respuesta',
        ),
    ]
